/**
 *
 * @author Jure Jesensek
 */
public class Bezier_GUI extends javax.swing.JFrame {

	/**
	 * Creates new form Bezier_GUI
	 */
	public Bezier_GUI() {
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanelMain = new Pane();
		jLabelStatus = new javax.swing.JLabel();
		jMenuBar = new javax.swing.JMenuBar();
		jMenuFile = new javax.swing.JMenu();
		jMenuItemClear = new javax.swing.JMenuItem();
		jMenuItemExit = new javax.swing.JMenuItem();
		jMenuHelp = new javax.swing.JMenu();
		jMenuItemAbout = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Bezier GUI");
		setPreferredSize(new java.awt.Dimension(600, 600));
		getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.PAGE_AXIS));

		jPanelMain.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseReleased(java.awt.event.MouseEvent evt) {
				jPanelMainMouseReleased(evt);
			}
		});

		javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
		jPanelMain.setLayout(jPanelMainLayout);
		jPanelMainLayout.setHorizontalGroup(
				jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 400, Short.MAX_VALUE)
		);
		jPanelMainLayout.setVerticalGroup(
				jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
						.addGap(0, 251, Short.MAX_VALUE)
		);

		getContentPane().add(jPanelMain);

		jLabelStatus.setText("Dolzina krivulje:");
		getContentPane().add(jLabelStatus);

		jMenuFile.setText("File");

		jMenuItemClear.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.CTRL_MASK));
		jMenuItemClear.setText("Clear");
		jMenuItemClear.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				resetPane(evt);
			}
		});
		jMenuFile.add(jMenuItemClear);

		jMenuItemExit.setText("Exit");
		jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exit(evt);
			}
		});
		jMenuFile.add(jMenuItemExit);

		jMenuBar.add(jMenuFile);

		jMenuHelp.setText("Help");

		jMenuItemAbout.setText("About");
		jMenuItemAbout.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				about(evt);
			}
		});
		jMenuHelp.add(jMenuItemAbout);

		jMenuBar.add(jMenuHelp);

		setJMenuBar(jMenuBar);

		pack();
	}// </editor-fold>

	private void jPanelMainMouseReleased(java.awt.event.MouseEvent evt) {
		jLabelStatus.setText(jPanelMain.toString());
	}

	private void resetPane(java.awt.event.ActionEvent evt) {
		jPanelMain.removeAll();
		jPanelMain.updateUI();
		jLabelStatus.setText("Dolzina krivulje: ");
	}

	private void exit(java.awt.event.ActionEvent evt) {
		System.exit(0);
	}

	private void about(java.awt.event.ActionEvent evt) {
		// todo
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
        /* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Bezier_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Bezier_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Bezier_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Bezier_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

        /* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new Bezier_GUI().setVisible(true);
			}
		});
	}

	// Variables declaration - do not modify
	private javax.swing.JLabel jLabelStatus;
	private javax.swing.JMenuBar jMenuBar;
	private javax.swing.JMenu jMenuFile;
	private javax.swing.JMenu jMenuHelp;
	private javax.swing.JMenuItem jMenuItemAbout;
	private javax.swing.JMenuItem jMenuItemClear;
	private javax.swing.JMenuItem jMenuItemExit;
	private javax.swing.JPanel jPanelMain;
	// End of variables declaration
}
